#!/usr/bin/env python3
"""
Converts a Whisper JSON output file to SRT format, filtering out potentially
hallucinated segments (e.g., segments starting at time 0 with high compression
ratios).

Usage:
    python whisper_to_srt.py input.json [output.srt] [max_chars_per_line]

Arguments:
    input.json             : The input JSON file generated by Whisper.
    output.srt (optional)  : The output SRT file.  If not provided, the output
                             filename will be based on the input filename.
    max_chars_per_line (optional): The maximum number of characters per line
                             in the SRT output (default: 80).

Example:
    python whisper_to_srt.py my_audio.json my_audio.srt 40
"""

# /// script
# dependencies = []
# ///

import json
import textwrap
import sys
from datetime import timedelta

def format_time(seconds):
    """Convert seconds to SRT timestamp format: HH:MM:SS,mmm"""
    td = timedelta(seconds=seconds)
    hours, remainder = divmod(td.seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    milliseconds = int(td.microseconds / 1000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{milliseconds:03d}"

def split_text_into_chunks(text, max_chars=80):
    """Split text into chunks of maximum length while respecting word boundaries"""
    return textwrap.wrap(text, width=max_chars, break_long_words=False)

def whisper_to_srt(json_data, output_file=None, max_chars=80):
    """Convert Whisper JSON format to SRT format, filtering out bad segments."""
    if isinstance(json_data, str):
        try:
            data = json.loads(json_data)
        except json.JSONDecodeError:
            with open(json_data, 'r', encoding='utf-8') as f:
                data = json.load(f)
    else:
        data = json_data

    # --- FILTERING STEP ---
    filtered_segments = []
    for segment in data['segments']:
        # Keep segments that:
        # 1. Have a non-zero start time.
        # 2. Have a compression ratio less than a threshold (e.g., 1.4).
        # 3. Do NOT have a start time of 0 if there are segments with non-zero start time
        if segment['start'] != 0 or all(s['start'] == 0 for s in data['segments']) and segment['compression_ratio'] < 1.4:
            filtered_segments.append(segment)

    data['segments'] = filtered_segments
    # --- END FILTERING ---

    srt_lines = []
    subtitle_index = 1

    for segment in data['segments']:
        start_time = segment['start']
        end_time = segment['end']
        text = segment['text'].strip()

        chunks = split_text_into_chunks(text, max_chars)

        if not chunks:  # Skip empty segments
            continue

        if len(chunks) == 1:
            srt_lines.append(f"{subtitle_index}")
            srt_lines.append(f"{format_time(start_time)} --> {format_time(end_time)}")
            srt_lines.append(chunks[0])
            srt_lines.append("")  # Empty line
            subtitle_index += 1
        else:
            chunk_duration = (end_time - start_time) / len(chunks)
            for i, chunk in enumerate(chunks):
                chunk_start = start_time + i * chunk_duration
                chunk_end = chunk_start + chunk_duration
                srt_lines.append(f"{subtitle_index}")
                srt_lines.append(f"{format_time(chunk_start)} --> {format_time(chunk_end)}")
                srt_lines.append(chunk)
                srt_lines.append("")  # Empty line
                subtitle_index += 1

    srt_content = "\n".join(srt_lines)

    if output_file:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(srt_content)
        return f"SRT file saved to {output_file}"
    else:
        return srt_content

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python whisper_to_srt.py input.json [output.srt] [max_chars_per_line]")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else input_file.rsplit('.', 1)[0] + '.srt'
    max_chars = int(sys.argv[3]) if len(sys.argv) > 3 else 80

    with open(input_file, 'r', encoding='utf-8') as f:
        json_data = json.load(f)

    result = whisper_to_srt(json_data, output_file, max_chars)
    print(result)